"""
Strategy specification models.

This module defines the Pydantic models that represent a trading strategy
in structured form. These are produced by the Prompt System (LLM) and
consumed by the Execution Engine and Backtester.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator


# ─── Enums ───────────────────────────────────────────────────────────────

class IndicatorType(str, Enum):
    SMA = "sma"
    EMA = "ema"
    WMA = "wma"
    RSI = "rsi"
    MACD = "macd"
    BOLLINGER = "bollinger"
    STOCHASTIC = "stochastic"
    ATR = "atr"
    ADX = "adx"


class ConditionType(str, Enum):
    CROSSEOVER = "crossover"
    CROSSUNDER = "crossunder"
    THRESHOLD = "threshold"  # above / below a value
    CROSS_VALUE = "cross_value"  # indicator crosses a fixed level


class ComparisonOp(str, Enum):
    GT = ">"
    GTE = ">="
    LT = "<"
    LTE = "<="
    EQ = "=="


class ExitType(str, Enum):
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"
    TRAILING_STOP = "trailing_stop"
    ATR_STOP = "atr_stop"
    TIME_BASED = "time_based"
    CONDITION_BASED = "condition_based"


class Timeframe(str, Enum):
    M1 = "1m"
    M5 = "5m"
    M15 = "15m"
    M30 = "30m"
    H1 = "1h"
    H4 = "4h"
    D1 = "1d"
    W1 = "1w"


class OrderSide(str, Enum):
    BUY = "buy"
    SELL = "sell"


# ─── Indicator Definition ────────────────────────────────────────────────

class IndicatorSpec(BaseModel):
    """Defines one indicator to be computed on the data feed."""

    indicator_type: IndicatorType
    period: int = Field(default=14, ge=1, description="Lookback period")
    fast_period: Optional[int] = Field(default=None, ge=1)
    slow_period: Optional[int] = Field(default=None, ge=1)
    source: str = Field(
        default="close",
        description="OHLCV field to compute from: open, high, low, close, volume"
    )
    params: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional params (e.g. deviation for Bollinger Bands)"
    )

    def compute_params(self) -> dict[str, Any]:
        """Return a flat dict of all params needed by TA-Lib or manual calc."""
        result = {"period": self.period, "source": self.source}
        if self.fast_period:
            result["fast_period"] = self.fast_period
        if self.slow_period:
            result["slow_period"] = self.slow_period
        result.update(self.params)
        return result


# ─── Conditions ──────────────────────────────────────────────────────────

class EntryCondition(BaseModel):
    """A single entry condition. ALL entry conditions must be satisfied."""

    condition_type: ConditionType
    indicator: IndicatorType
    indicator_b: Optional[IndicatorType] = None  # for crossover between two indicators
    value: Optional[float] = None  # fixed threshold value
    operator: Optional[ComparisonOp] = None
    params: dict[str, Any] = Field(default_factory=dict)
    description: str = Field(
        default="",
        description="Human-readable description of this condition"
    )


class ExitCondition(BaseModel):
    """A single exit condition. ANY exit condition triggers closure."""

    exit_type: ExitType
    pips: Optional[float] = None  # for stop_loss, take_profit
    multiplier: Optional[float] = None  # e.g. 2x SL for TP
    atr_periods: Optional[int] = Field(default=14, ge=1)
    atr_multiplier: Optional[float] = Field(default=2.0)
    candles: Optional[int] = None  # for time_based exit
    condition: Optional[EntryCondition] = None  # for condition_based exit
    description: str = Field(default="")


# ─── Risk Management ─────────────────────────────────────────────────────

class RiskManagement(BaseModel):
    """Risk parameters applied per strategy."""

    position_size_pct: float = Field(
        default=2.0, ge=0.1, le=25.0,
        description="Percentage of balance per trade"
    )
    max_open_trades: int = Field(
        default=3, ge=1, le=20,
        description="Maximum concurrent open positions"
    )
    max_daily_loss_pct: float = Field(
        default=5.0, ge=0.5, le=20.0,
        description="Stop trading for the day after this % loss"
    )
    max_drawdown_pct: float = Field(
        default=15.0, ge=1.0, le=50.0,
        description="Hard stop for the strategy after this % drawdown from peak"
    )


# ─── Strategy Spec (top-level) ──────────────────────────────────────────

class StrategySpec(BaseModel):
    """
    Complete specification of a trading strategy.
    Generated by the LLM from natural language, validated here.
    """

    name: str = Field(..., min_length=3, max_length=128)
    description: str = Field(
        ..., max_length=2048,
        description="Human-readable description of the strategy"
    )
    symbol: str = Field(..., description="Trading pair, e.g. EURUSD, BTCUSD")
    timeframe: Timeframe = Field(..., description="Chart timeframe for signals")

    indicators: list[IndicatorSpec] = Field(
        ..., min_length=1, max_length=10,
        description="All indicators used by this strategy"
    )
    entry_conditions: list[EntryCondition] = Field(
        ..., min_length=1, max_length=8,
        description="ALL conditions must be met for entry signal"
    )
    exit_conditions: list[ExitCondition] = Field(
        ..., min_length=1, max_length=6,
        description="ANY condition triggers exit"
    )
    risk_management: RiskManagement = Field(
        default_factory=RiskManagement,
        description="Risk parameters for position sizing and limits"
    )

    @field_validator("symbol")
    @classmethod
    def validate_symbol(cls, v: str) -> str:
        if not v.replace("/", "").replace("X", "").isalnum():
            raise ValueError(f"Invalid symbol format: {v}")
        return v.upper()

    def summary(self) -> str:
        """Return a one-line summary for display."""
        n_entries = len(self.entry_conditions)
        n_exits = len(self.exit_conditions)
        return (
            f"{self.name} | {self.symbol} | {self.timeframe.value} | "
            f"{n_entries} entry cond. | {n_exits} exit cond. | "
            f"Risk: {self.risk_management.position_size_pct}%"
        )
