"""
MQL5 Code Generator.

Generates complete, compilable MQL5 Expert Advisor source code from a
StrategySpec, including all indicators, entry/exit logic, and risk management.
"""

from __future__ import annotations

import logging
from .models import StrategySpec

logger = logging.getLogger(__name__)

# ── Indicator MQL5 mapping ─────────────────────────────────────────────

INDICATOR_DECL = {
    "sma": {
        "type": "MODE_SMA",
        "params": "MA_METHOD_SIMPLE",
        "handle": "iMA(_Symbol, _Period, {period}, 0, MA_METHOD_SIMPLE, PRICE_CLOSE)",
    },
    "ema": {
        "type": "MODE_EMA",
        "params": "MA_METHOD_EMA",
        "handle": "iMA(_Symbol, _Period, {period}, 0, MA_METHOD_EMA, PRICE_CLOSE)",
    },
    "wma": {
        "type": "MODE_LWMA",
        "params": "MA_METHOD_LINEAR",
        "handle": "iMA(_Symbol, _Period, {period}, 0, MA_METHOD_LINEAR, PRICE_CLOSE)",
    },
    "rsi": {
        "handle": "iRSI(_Symbol, _Period, {period}, PRICE_CLOSE)",
        "buffer": "0",
    },
    "macd": {
        "handle": "iMACD(_Symbol, _Period, {period}, {params.get('signal_period', 9)}, 26, PRICE_CLOSE)",
        "buffers": "0,1,2",  # main, signal, histogram
    },
    "bollinger": {
        "handle": "iBands(_Symbol, _Period, {period}, 0, {params.get('deviations', 2.0)}, PRICE_CLOSE)",
        "buffers": "0,1,2",  # middle, upper, lower
    },
    "stochastic": {
        "handle": "iStochastic(_Symbol, _Period, {params.get('k_period', 14)}, {params.get('d_period', 3)}, 3, MODE_SMA, PRICE_CLOSE)",
        "buffers": "0,1",
    },
    "atr": {
        "handle": "iATR(_Symbol, _Period, {period})",
    },
    "adx": {
        "handle": "iADX(_Symbol, _Period, {period})",
        "buffers": "0,1,2",
    },
}


def generate_mql5(spec: StrategySpec) -> str:
    """
    Generate a complete MQL5 EA from a StrategySpec.

    Returns compilable .mq5 source code as a string.
    """
    lines = []

    # ── Header ─────────────────────────────────────────────────────────
    lines.extend([
        "//+----------------------------------------------------------------+",
        f"|{spec.name:<56}|",
        f"|{f'Generated by Trading AI':^56}|",
        f"|{f'{spec.symbol} | {spec.timeframe}':^56}|",
        "//+----------------------------------------------------------------+",
        '#property copyright "Trading AI"',
        f'#property link "https://trading-ai.local"',
        "#property version   1.00",
        "#property strict",
        "",
        "/*",
        f" * Strategy: {spec.name}",
        f" * Symbol:   {spec.symbol}",
        f" * Timeframe: {spec.timeframe}",
        f" * Trades:   {len(spec.entry_conditions)} entry rule(s), {len(spec.exit_conditions)} exit rule(s)",
        " */",
        "",
    ])

    # ── Input parameters ──────────────────────────────────────────────
    rm = spec.risk_management
    lines.extend([
        "//+--- Input Parameters ---",
        f'input double  LotSize          = {rm.position_size_pct / 100:.4f};      // Position size',
        f'input int     MaxOpenTrades    = {rm.max_open_trades};                  // Max concurrent trades',
        f'input double  MaxDailyLoss     = {rm.max_daily_loss_pct};              // Max daily loss %',
        f'input double  MaxDrawdown      = {rm.max_drawdown_pct};               // Max drawdown %',
        "",
    ])

    # Exit parameters
    for exc in spec.exit_conditions:
        if exc.exit_type == "stop_loss":
            lines.append(f'input int     StopLossPips   = {int(exc.pips)};          // Stop loss in pips')
        elif exc.exit_type == "take_profit":
            lines.append(f'input int     TakeProfitPips = {int(exc.pips)};          // Take profit in pips')
        elif exc.exit_type == "atr_stop":
            lines.append(f'input double  ATRMultiplier  = {exc.atr_multiplier};    // ATR stop multiplier')
        elif exc.exit_type == "trailing_stop":
            lines.append(f'input int     TrailingPips   = {int(exc.pips)};          // Trailing stop pips')

    lines.extend(["", "//+--- Global Variables ---"])

    # ── Indicator handles ─────────────────────────────────────────────
    indicator_vars = []
    for ind in spec.indicators:
        tmpl = INDICATOR_DECL.get(ind.indicator_type, {})
        handle_expr = tmpl.get("handle", f"iCustom(_Symbol, _Period, '{ind.indicator_type}.ex5', {ind.period})")
        var_name = f"handle_{ind.indicator_type}_{ind.period}"
        indicator_vars.append((var_name, ind))
        lines.append(f"int {var_name};")

    lines.extend([
        "",
        "int ticket_buy, ticket_sell;",
        "double daily_start_balance;",
        "double initial_balance;",
        "",
    ])

    # ── OnInit ────────────────────────────────────────────────────────
    lines.extend([
        "//+--- Initialization ---",
        "int OnInit()",
        "{",
        "   initial_balance = AccountBalance();",
        "   daily_start_balance = initial_balance;",
        "   ",
    ])

    for var_name, ind in indicator_vars:
        tmpl = INDICATOR_DECL.get(ind.indicator_type, {})
        handle_expr = tmpl.get("handle", f"iCustom(_Symbol, _Period, '{ind.indicator_type}.ex5', {ind.period})")
        lines.append(f"   {var_name} = {handle_expr};")
        lines.append(f"   if({var_name} == INVALID_HANDLE) {{")
        lines.append(f'      Print("Failed to create {ind.indicator_type}({ind.period}) indicator");')
        lines.append(f"      return(INIT_FAILED);")
        lines.append(f"   }}")

    lines.extend([
        "   ",
        '   Print("EA initialized: ' + spec.name + '");',
        "   return(INIT_SUCCEEDED);",
        "}",
        "",
    ])

    # ── OnDeinit ──────────────────────────────────────────────────────
    lines.extend([
        "//+--- Deinitialization ---",
        "void OnDeinit(const int reason)",
        "{",
    ])
    for var_name, _ in indicator_vars:
        lines.append(f"   IndicatorRelease({var_name});")
    lines.extend([
        "}",
        "",
    ])

    # ── Helper functions ──────────────────────────────────────────────
    lines.extend([
        "//+--- Helper: Count Open Trades ---",
        "int CountOpenTrades(ENUM_ORDER_TYPE type)",
        "{",
        "   int count = 0;",
        "   for(int i = OrdersTotal() - 1; i >= 0; i--)",
        "   {",
        "      ulong ticket = OrderGetTicket(i);",
        "      if(OrderGetString(ORDER_SYMBOL) == _Symbol && OrderGetInteger(ORDER_TYPE) == type)",
        "         count++;",
        "   }",
        "   return count;",
        "}",
        "",
        "//+--- Helper: Get Indicator Value ---",
        "double GetIndicatorValue(int handle, int buffer, int shift)",
        "{",
        "   double value[];",
        "   ArraySetAsSeries(value, true);",
        "   if(CopyBuffer(handle, buffer, 0, shift + 1, value) > 0)",
        "      return value[shift];",
        "   return 0;",
        "}",
        "",
    ])

    # ── OnTick: Entry Logic ───────────────────────────────────────────
    lines.extend([
        "//+--- Main Logic ---",
        "void OnTick()",
        "{",
        "   // Check if new bar",
        "   static datetime last_bar_time;",
        "   datetime current_bar_time = iTime(_Symbol, _Period, 0);",
        "   if(last_bar_time == current_bar_time) return;",
        "   last_bar_time = current_bar_time;",
        "   ",
        "   // Daily reset",
        "   if(TimeDayOfYear(TimeCurrent()) != TimeDayOfYear(last_bar_time))",
        "      daily_start_balance = AccountBalance();",
        "   ",
        "   // Max drawdown check",
        "   double current_dd = (initial_balance - AccountBalance()) / initial_balance * 100;",
        '   if(current_dd > MaxDrawdown) { Print("Max drawdown reached. Stopping."); return; }',
        "   ",
        "   // Max daily loss check",
        "   double daily_loss = (daily_start_balance - AccountBalance()) / daily_start_balance * 100;",
        '   if(daily_loss > MaxDailyLoss) { Print("Max daily loss reached. Stopping for today."); return; }',
        "   ",
        "   // Max open trades check",
        "   if(CountOpenTrades(POSITION_TYPE_BUY) + CountOpenTrades(POSITION_TYPE_SELL) >= MaxOpenTrades)",
        "      return;",
        "   ",
    ])

    # Get indicator values for current bar
    for var_name, ind in indicator_vars:
        val_name = f"val_{ind.indicator_type}_{ind.period}"
        lines.append(f"   double {val_name} = GetIndicatorValue({var_name}, 0, 0);")

    lines.append("")

    # ── Entry conditions ──────────────────────────────────────────────
    lines.append("   // --- Entry Conditions ---")

    for i, entry in enumerate(spec.entry_conditions):
        lines.append(f"   // Entry #{i+1}: {entry.description or entry.condition_type}")

        if entry.condition_type == "crossover":
            # Crossover between two indicators
            fast_period = entry.params.get("fast_period", 1)
            slow_period = entry.params.get("slow_period", 50)

            fast_var = f"val_{entry.indicator}_{fast_period}"
            slow_var = f"val_{entry.indicator}_{slow_period}"

            # Also need previous bar values
            lines.append(f"   double {fast_var}_prev = GetIndicatorValue(handle_{entry.indicator}_{fast_period}, 0, 1);")
            lines.append(f"   double {slow_var}_prev = GetIndicatorValue(handle_{entry.indicator}_{slow_period}, 0, 1);")
            lines.append("")
            lines.append(f"   // {entry.description}")
            lines.append(f"   bool entry_{i} = ({fast_var} > {slow_var} && {fast_var}_prev <= {slow_var}_prev);")

        elif entry.condition_type == "threshold":
            val_name = f"val_{entry.indicator}_{entry.params.get('period', 14)}"
            op = {">": ">", "<": "<", ">=": ">=", "<=": "<=", "==": "==", "!=": "!="}.get(entry.operator, ">")
            lines.append(f"   bool entry_{i} = ({val_name} {op} {entry.value});")
            lines.append(f"   // {entry.description or entry.condition_type}")

        else:
            lines.append(f"   bool entry_{i} = true;  // TODO: implement {entry.condition_type}")

    # Combine entry conditions (AND all)
    entry_bools = [f"entry_{i}" for i in range(len(spec.entry_conditions))]
    if len(entry_bools) > 1:
        lines.append(f"   bool entry_signal = {' && '.join(entry_bools)};")
    else:
        lines.append(f"   bool entry_signal = {entry_bools[0]};")

    # Buy order
    lines.extend([
        "",
        "   if(entry_signal)",
        "   {",
        '      Print("BUY signal triggered for ' + spec.symbol + '");',
        "      double sl = 0, tp = 0;",
    ])

    # Calculate SL/TP
    for exc in spec.exit_conditions:
        if exc.exit_type == "stop_loss":
            lines.append(f"      sl = Ask - StopLossPips * _Point;")
        elif exc.exit_type == "take_profit":
            lines.append(f"      tp = Ask + TakeProfitPips * _Point;")

    lines.extend([
        "      MqlTradeRequest request;",
        "      MqlTradeResult result;",
        "      request.action = TRADE_ACTION_DEAL;",
        "      request.symbol = _Symbol;",
        "      request.volume = LotSize;",
        "      request.type = ORDER_TYPE_BUY;",
        "      request.price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);",
        "      request.sl = sl;",
        "      request.tp = tp;",
        "      request.deviation = 10;",
        "      request.magic = " + f"100{i}001;",
        "      request.comment = \"" + spec.name[:40] + "\";",
        "      OrderSend(request, result);",
        "   }",
    ])

    lines.append("")

    # ── Exit/Management ───────────────────────────────────────────────
    lines.extend([
        "   // --- Trade Management ---",
        "   ManageOpenPositions();",
        "}",
        "",
    ])

    # ── Trade Management Function ─────────────────────────────────────
    lines.extend([
        "//+--- Trade Management ---",
        "void ManageOpenPositions()",
        "{",
        "   for(int i = OrdersTotal() - 1; i >= 0; i--)",
        "   {",
        "      ulong ticket = OrderGetTicket(i);",
        "      if(OrderGetString(ORDER_SYMBOL) != _Symbol) continue;",
        "      ",
        "      double entry_price = OrderGetDouble(ORDER_PRICE_OPEN);",
        "      double current_price = OrderGetInteger(ORDER_TYPE) == POSITION_TYPE_BUY",
        "         ? SymbolInfoDouble(_Symbol, SYMBOL_BID)",
        "         : SymbolInfoDouble(_Symbol, SYMBOL_ASK);",
        "      ",
        "      double profit_pct = (current_price - entry_price) / entry_price * 100;",
        "      ",
    ])

    for exc in spec.exit_conditions:
        if exc.exit_type == "stop_loss":
            lines.append(f"      // Stop loss: {exc.pips} pips")
            lines.append(f"      if(OrderGetDouble(ORDER_SL) == 0)")
            lines.append(f"         ModifyPosition(ticket, entry_price - {exc.pips} * _Point, 0);")
        elif exc.exit_type == "take_profit":
            lines.append(f"      // Take profit: {exc.pips} pips")
            lines.append(f"      if(OrderGetDouble(ORDER_TP) == 0)")
            lines.append(f"         ModifyPosition(ticket, 0, entry_price + {exc.pips} * _Point);")

    lines.extend([
        "   }",
        "}",
        "",
        "//+--- Modify Position ---",
        "void ModifyPosition(ulong ticket, double sl, double tp)",
        "{",
        "   MqlTradeRequest request;",
        "   MqlTradeResult result;",
        "   request.action = TRADE_ACTION_SLTP;",
        "   request.position = ticket;",
        "   request.sl = sl;",
        "   request.tp = tp;",
        "   OrderSend(request, result);",
        "}",
        "",
        "//+----------------------------------------------------------------+",
        "// End of EA: " + spec.name + "",
    ])

    code = "\n".join(lines)
    logger.info(f"Generated MQL5 EA: {len(lines)} lines for {spec.name}")
    return code


def generate_mql5_filename(spec: StrategySpec) -> str:
    """Generate a standard MQL5 filename."""
    safe_name = spec.name.replace(" ", "_").replace("/", "_").replace(":", "_")[:40]
    return f"{safe_name}_{spec.symbol}_{spec.timeframe.replace('h', 'H').replace('m', 'M')}.mq5"
